# Generated by Django 5.1.5 on 2025-03-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_admin', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='food_item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
