# Generated by Django 5.1.5 on 2025-03-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_admin', '0004_recentactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentActivity',
        ),
    ]
