# Generated by Django 5.1.5 on 2025-04-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_admin', '0006_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
