# Generated by Django 5.1.5 on 2025-01-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_profile_email_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='informatics.cafetera@icp.edu.np', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='informatics@123', max_length=50),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='cafeteria_users',
        ),
    ]
