# Generated by Django 5.1.5 on 2025-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
