# Generated by Django 5.1.5 on 2025-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0009_fooditem_is_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='is_in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
