# Generated by Django 5.1.5 on 2025-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0011_alter_fooditem_is_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
