# Generated by Django 5.1.5 on 2025-02-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0012_fooditem_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='is_featured',
        ),
    ]
