# Generated by Django 5.1.5 on 2025-03-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cafeteria_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cafeteria_cart_items',
        ),
    ]
