# Generated by Django 5.1.5 on 2025-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0015_alter_cart_table_alter_cartitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
