# Generated by Django 5.1.5 on 2025-03-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0017_alter_fooditem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
