# Generated by Django 5.1.5 on 2025-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0018_cartitem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
