# Generated by Django 5.1.5 on 2025-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0019_profile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
