# Generated by Django 5.1.5 on 2025-03-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0021_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dine_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Payment on Delivery'), ('Online', 'Online Payment')], default='Cash', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
