# Generated by Django 5.1.5 on 2025-03-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0023_remove_order_cart_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
