# Generated by Django 5.1.5 on 2025-03-31 06:21

import cafeteria.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0027_lostfound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=cafeteria.models.generate_group_code, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_group_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafeteria_group_orders',
            },
        ),
        migrations.CreateModel(
            name='GroupOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.fooditem')),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='cafeteria.grouporder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafeteria_group_order_items',
            },
        ),
    ]
