# Generated by Django 5.1.5 on 2025-03-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0029_cartitem_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='group_code',
        ),
    ]
