# Generated by Django 5.1.5 on 2025-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0030_remove_cartitem_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='group_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='group_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
