# Generated by Django 5.1.5 on 2025-03-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0031_cartitem_group_code_order_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='group_code',
        ),
    ]
