# Generated by Django 5.1.5 on 2025-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0032_remove_cartitem_group_code_remove_order_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouporderitem',
            name='group_order',
        ),
        migrations.RemoveField(
            model_name='grouporderitem',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='grouporderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='group_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='GroupOrder',
        ),
        migrations.DeleteModel(
            name='GroupOrderItem',
        ),
    ]
