# Generated by Django 5.1.5 on 2025-04-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0039_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='order',
        ),
    ]
