# Generated by Django 5.1.5 on 2025-04-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0043_userengagement_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEngagement',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
