# Generated by Django 5.1.5 on 2025-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0044_remove_usersession_user_delete_userengagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='informaticscafeteria@gmail.com', max_length=50),
        ),
    ]
