# Generated by Django 5.1.5 on 2025-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0045_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
