# Generated by Django 5.1.5 on 2025-04-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0046_fooditem_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='stock_quantity',
        ),
    ]
