# Generated by Django 5.1.5 on 2025-04-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0047_remove_fooditem_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='username',
        ),
    ]
