# Generated by Django 5.1.5 on 2025-04-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0048_remove_cart_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='username',
        ),
    ]
