# Generated by Django 5.1.5 on 2025-04-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0049_remove_cartitem_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='username',
        ),
    ]
