# Generated by Django 5.1.5 on 2025-04-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0050_remove_orderitem_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
