# Generated by Django 5.1.5 on 2025-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0052_order_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scheduled_date',
        ),
    ]
